

Redmine Asciidoc Formatter
==========================
Gregory Romé
v0.4.0, 27-dec-2013

Copyright (C) 2010-2013  Gregory Romé

License
-------

--------------------------------------------------------------------------------
Copyright (C) 2010-2013  Gregory Romé

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
--------------------------------------------------------------------------------

Installation
------------

See redmine plugin installation howto. The current +master+ branch targets Redmine +2.3.x+.

This plugin requires asciidoc (+sudo apt-get install asciidoc+).

You should also install pygments (+sudo apt-get install python-pygments+) and 
source-highlight (+sudo apt-get install source-highlight+).

Documentation
-------------

The formattter supports all asciidoc standard syntaxes. It supports also Redmine macros
(+\{{Macro()}}+, automatic links (+#<ID>+, +source:<path/to/file>+, +commit:<ref>+...) and also a
new syntax for wiki links: 

- +wiki:WikiPageName+ where +WikiPageName+ is the name of the linked wiki page.

It is possible to generate a ToC by adding +:toc:+ in the wiki page.

Known Limitations
-----------------

The ToC is sometimes not generated (no root cause identified).

Notes
-----

This plugin was derived directly from:

 - redmine_restructuredtext_formatter (http://github.com/alphabetum/redmine_restructuredtext_formatter.git)
 - RbSt (http://rdoc.info/github/alphabetum/rbst)

